### ISSUE TITLE
Post-processing failure during collectstatic

### ISSUE THREAD

**Issue by bryanlandia** [raccoongang/xblock-video#197]
Run 

`./manage.py cms collectstatic --settings=aws`

or 

`./manage.py lms collectstatic --settings=aws`

```
Post-processed 'js/student-view/video-xblock.js' as 'js/student-view/video-xblock.4fa3aa72ab58.js'
Post-processing 'vendor/css/video-js.min.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
ValueError: The file 'vendor/css/font/VideoJS.eot' could not be found with <openedx.core.storage.ProductionStorage object at 0x7f278c03e990>.
```

**Comment by bryanlandia** [comment]
This happened in both `0.6.3` and `0.6.4`

**Comment by z4y4ts** [comment]
Hi @bryanlandia 

We're going to release fix for this in v0.6.5. See #200 for the reference.

Testing the fix today on our stage env.

**Comment by z4y4ts** [comment]
So, as far as I can see from `collectstatic` output, now it does pick up VideoJS fonts.
I'm merging 0.6.5 now and opening a PR to upstream repo.

@bryanlandia, please let me know it that works for you.

**Comment by bryanlandia** [comment]
@z4y4ts Thank you.  I will merge and test and let you know.

**Comment by bryanlandia** [comment]
@z4y4ts Yes, this fixes the problem with the VideoJS fonts.  Thanks!

**Comment by bryanlandia** [comment]
@z4y4ts Please close this Issue when you have a chance.

**Comment by z4y4ts** [comment]
Yeah, sure. I've just forgot not everybody can close issues here. Thanks for nudging. Closing now.
